# Generated by Django 4.2.6 on 2023-10-17 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0002_breed_dog_age_dog_color_dog_favoritefood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="age",
            field=models.PositiveBigIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="DogBreed",
                to="dogs.breed",
            ),
        ),
    ]
